---

- name: configure and start microshift
  hosts:
    - all
  become: true
  pre_tasks:
    - name: push out pull secret
      ansible.builtin.copy:
        content: "{{ openshift_pull_secret }}"
        dest: /etc/crio/openshift-pull-secret
  tasks:
    - name: start microshift
      ansible.builtin.systemd:
        name: microshift
        state: started
        enabled: true
