token: "XXXXXXXXX"
rhsm_username: CHANGEME
rhsm_password: CHANGEME

image_username: CHANGEME
image_password: CHANGEME

controller_hostname: CHANGEME
controller_password: CHANGEME

vm_template_password: CHANGEME
vm_template_password: CHANGEME

kubeadmin_username: kubeadmin
kubeadmin_password: CHANGEME

tower:
  filename:
    kubeconfig: "{{ tmpdir.path }}/ocp/auth/kubeconfig"
