---

- name: compose an image based on vars file
  hosts:
    - all
  pre_tasks:
    - name: handle locally
      delegate_to: localhost
      become: false
      block:
        - name: pull code to system
          ansible.builtin.git:
            repo: https://github.com/redhat-manufacturing/device-edge-demos.git
            dest: /tmp/image-definition
        - name: load in image definition
          ansible.builtin.include_vars:
            file: /tmp/image-definition/demos/rhde-pipeline/device-edge-images/image-definition.yml
  roles:
    - infra.osbuild.builder
