
- name: Login to OpenShift cluster
  command: oc login --token {{ token }} --server {{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}

- name: Save kubeconfig
  copy:
    src: ~/.kube/config
    dest: "{{ tmpdir.path }}/ocp/auth/kubeconfig"

- name: import playbook to configure the local registry
  ansible.builtin.import_playbook: configure-registry.yml
