---

- name: Manage service that allows connection to the vm
  hosts:
    - all
  gather_facts: false
  module_defaults:
    kubernetes.core.k8s:
      state: "{{ resource_state | default('present') }}"
  tasks:
        
    - name: Test kubeconfig login to cluster
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
      register: k8s_info
      until: k8s_info is successfull
      retries: 10
      delay: 10

    - name: Create service for virtual machine
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ virtual_machine_name }}-ssh"
            namespace: image-builder
          spec:
            externalTrafficPolicy: Cluster
            ports:
              - port: 22
                protocol: TCP
            selector:
              kubevirt.io/domain: "{{ virtual_machine_name }}"
            type: NodePort
