---

- name: Manage service that allows connection to the vm
  hosts:
    - all
  gather_facts: false
  module_defaults:
    kubernetes.core.k8s:
      state: "{{ resource_state | default('present') }}"
  tasks:
    - name: Check kubeconfig file
      ansible.builtin.shell:
        cmd: kubectl config view
      register: kubeconfig_view

    - name: Debug check kubeconfig file
      debug:
        msg: "{{ kubeconfig_view.stdout }}"
        
    - name: Get a list of all pods from any namespace
      kubernetes.core.k8s_info:
        kind: Pod
      register: pod_list


    - name: Create service for virtual machine
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ virtual_machine_name }}-ssh"
            namespace: image-builder
          spec:
            externalTrafficPolicy: Cluster
            ports:
              - port: 22
                protocol: TCP
            selector:
              kubevirt.io/domain: "{{ virtual_machine_name }}"
            type: NodePort
